# Stable options
edition = "2024"
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
reorder_imports = true
fn_params_layout = "Compressed"
comment_width = 100

# Unstable options
unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
