use crate::{datetime_t, gpstime_t};
#[derive(Copy, Clone, Default)]
#[repr(C)]
pub struct ephem_t {
    pub vflg: i32,
    pub t: datetime_t,
    pub toc: gpstime_t,
    pub toe: gpstime_t,
    pub iodc: i32,
    pub iode: i32,
    pub deltan: f64,
    pub cuc: f64,
    pub cus: f64,
    pub cic: f64,
    pub cis: f64,
    pub crc: f64,
    pub crs: f64,
    pub ecc: f64,
    pub sqrta: f64,
    pub m0: f64,
    pub omg0: f64,
    pub inc0: f64,
    pub aop: f64,
    pub omgdot: f64,
    pub idot: f64,
    pub af0: f64,
    pub af1: f64,
    pub af2: f64,
    pub tgd: f64,
    pub svhlth: i32,
    pub codeL2: i32,
    pub n: f64,
    pub sq1e2: f64,
    pub A: f64,
    pub omgkdot: f64,
}
